-- auth-service schema (PostgreSQL). Database: auth_db. Owner of the users table.
-- Safe to run many times: it only creates what is missing.

CREATE TABLE IF NOT EXISTS users (
    user_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(20) NOT NULL,
    password VARCHAR(60) NOT NULL,
    role     VARCHAR(12) NOT NULL,
    status   VARCHAR(8)  NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT ck_users_role CHECK (role IN ('ADMIN', 'RECEPTIONIST', 'PATIENT', 'DOCTOR')),
    CONSTRAINT ck_users_status CHECK (status IN ('PENDING', 'ACTIVE', 'INACTIVE', 'REJECTED'))
);
