-- hospital-service schema (PostgreSQL). Database: hospital_db.
-- Owner of: departments, doctors, patients, patient_addresses.
-- Safe to run many times: it only creates what is missing.
-- user_id in doctors and patients points to a user in auth-service. It is a plain number
-- (no foreign key), because the users table is in another database.

CREATE TABLE IF NOT EXISTS departments (
    department_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    description   VARCHAR(255),
    status        VARCHAR(8)   NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT uq_departments_name UNIQUE (name),
    CONSTRAINT ck_departments_status
        CHECK (status IN ('PENDING', 'ACTIVE', 'INACTIVE', 'REJECTED'))
);

CREATE TABLE IF NOT EXISTS doctors (
    doctor_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        INTEGER,
    name           VARCHAR(100) NOT NULL,
    specialization VARCHAR(100) NOT NULL,
    phone          VARCHAR(20)  NOT NULL,
    email          VARCHAR(100) NOT NULL,
    department_id  INTEGER      NOT NULL,
    status         VARCHAR(8)   NOT NULL DEFAULT 'PENDING',

    CONSTRAINT uq_doctors_user UNIQUE (user_id),
    CONSTRAINT uq_doctors_phone UNIQUE (phone),
    CONSTRAINT uq_doctors_email UNIQUE (email),
    CONSTRAINT ck_doctors_status
        CHECK (status IN ('PENDING', 'ACTIVE', 'INACTIVE', 'REJECTED')),
    CONSTRAINT fk_doctors_department FOREIGN KEY (department_id)
        REFERENCES departments (department_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS patients (
    patient_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    INTEGER,
    name       VARCHAR(60)  NOT NULL,
    dob        DATE,
    gender     VARCHAR(6)   NOT NULL,
    phone      VARCHAR(20)  NOT NULL,
    email      VARCHAR(100) NOT NULL,
    status     VARCHAR(8)   NOT NULL DEFAULT 'PENDING',

    CONSTRAINT uq_patients_user UNIQUE (user_id),
    CONSTRAINT uq_patients_phone UNIQUE (phone),
    CONSTRAINT uq_patients_email UNIQUE (email),
    CONSTRAINT ck_patients_gender CHECK (gender IN ('MALE', 'FEMALE', 'OTHER')),
    CONSTRAINT ck_patients_status
        CHECK (status IN ('PENDING', 'ACTIVE', 'INACTIVE', 'REJECTED'))
);

CREATE TABLE IF NOT EXISTS patient_addresses (
    address_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id   INTEGER      NOT NULL,
    state        VARCHAR(100) NOT NULL,
    district     VARCHAR(100) NOT NULL,
    pincode      VARCHAR(10)  NOT NULL,
    address_type VARCHAR(9)   NOT NULL DEFAULT 'HOME',

    CONSTRAINT uq_patient_address_type UNIQUE (patient_id, address_type),
    CONSTRAINT ck_patient_addresses_type
        CHECK (address_type IN ('HOME', 'WORK', 'BILLING', 'EMERGENCY')),
    CONSTRAINT fk_patient_addresses_patient FOREIGN KEY (patient_id)
        REFERENCES patients (patient_id) ON UPDATE CASCADE ON DELETE CASCADE
);
